---
title: "Gw_Campaign_Events"
author: "Dylan Lucko"
date: "4/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(DT)
library(plotly)

events <- readRDS("events_saved.rds")



```

## Most Frequented Cities

```{r}
events %>% 
  count(city, sort= TRUE) %>% 
  head(10)




```


### Intro
```{r}
events %>% 
  filter(str_detect(str_to_lower(description), "debt"))
# finding specific words aka strings; case sensitive



```

### Canditates Coming to MI
```{r}
visits_to_MI <- events %>% 
  filter(state == "MI") %>% 
  group_by(cand_lastname) %>% 
  count(cand_lastname)

#fig <- plot_ly(data=visits_to_MI, labels = ~cand_lastname, values ~n)
#fig <- fig %>%  add_pie(hole = 0.6)
#fig <- fig %>% layout(title="MI", showlegend=F)
```

### Visits by Kamala Harris
```{r}
events_month <- events %>% 
  mutate(month(date))

kamala_months <- events_month %>% 
  filter(cand_lastname== "Harris") %>% 
  #group_by (month(date)) %>% 
  count(month = month(date))

kamala_months
saveRDS(kamala_months, "kamala_months.rds")

mychart1<-kamala_months %>% 
  plot_ly(x = ~month, 
          y = ~n,
          type = "bar")

mychart1<- mychart1 %>% 
  layout(title= "Total Trips by Harris each Month")
mychart1
saveRDS(mychart1, "mychart1.rds")
```


```{r}

```







